import os
import json
import yaml
import logging
from typing import Dict, Any, List

class ConfigGenerator:
    """
    配置生成器：负责将 map_config.json 转换为 mapproxy.yaml 和 mapproxy-seed.yaml。
    """

    def __init__(self, work_dir: str, map_config: Dict[str, Any]):
        self.work_dir = work_dir
        self.map_config = map_config
        self.logger = logging.getLogger("ConfigGenerator")
        
        # 预定义常量
        self.CHINA_BBOX = [73.0, 18.0, 135.0, 54.0]
        self.GLOBAL_GRID_NAME = "webmercator"
        self.CACHE_NAME = "arcgis_satellite_cache"
        self.LAYER_NAME = "arcgis_satellite"

    def _get_res_for_zoom(self, z: int) -> float:
        """计算 WebMercator 在给定层级的分辨率"""
        return 156543.03392804097 / (2 ** z)

    def generate_mapproxy_config(self) -> Dict[str, Any]:
        """根据 map_config.json 生成 mapproxy.yaml 的结构"""
        
        sources_cfg = self.map_config.get("sources", {})
        features_cfg = self.map_config.get("features", {})
        
        # 1. 定义基础结构
        config = {
            "services": {
                "demo": None,
                "wms": {
                    "md": {
                        "title": "MapProxy WMS Proxy",
                        "abstract": "Generated by MapProxy Config Generator"
                    }
                },
                "wmts": {},
            },
            "layers": [],
            "caches": {},
            "sources": {},
            "grids": {
                self.GLOBAL_GRID_NAME: {
                    "base": "GLOBAL_WEBMERCATOR"
                }
            },
            "globals": {
                "cache": {
                    "base_dir": "./cache_data",
                    "lock_dir": "./cache_data/locks"
                },
                "image": {
                    "resampling_method": "bicubic"
                }
            }
        }

        # 1.1 配置 HTTP Globals (Timeout, SSL)
        system_cfg = self.map_config.get("system", {})
        http_cfg = system_cfg.get("http", {})
        
        # 默认超时时间 60s (MapProxy 默认通常较短)
        client_timeout = http_cfg.get("client_timeout", 60)
        ssl_no_cert_checks = http_cfg.get("ssl_no_cert_checks", False)

        if client_timeout or ssl_no_cert_checks:
            config["globals"]["http"] = {}
            if client_timeout:
                config["globals"]["http"]["client_timeout"] = client_timeout
            if ssl_no_cert_checks:
                config["globals"]["http"]["ssl_no_cert_checks"] = True

        # 2. 准备 Sources 参数
        global_url = sources_cfg.get("global_url", "").strip()
        if not global_url:
             # Fallback default
             global_url = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/%(z)s/%(y)s/%(x)s"

        smart_switch = features_cfg.get("smart_switch", False)
        china_url = sources_cfg.get("china_url", "").strip() if smart_switch else ""

        def add_sources_for_target(target_name: str, min_res: float = None, max_res: float = None) -> List[str]:
            """为特定任务或默认目标动态生成 Sources，并注入 min_res 和 max_res"""
            sources_list = []
            
            # China Source (如果开启 Smart Switch)
            if smart_switch and china_url:
                china_source_name = f"{target_name}_china_source"
                china_def = {
                    "type": "tile",
                    "grid": self.GLOBAL_GRID_NAME,
                    "url": china_url,
                    "coverage": {
                        "bbox": self.CHINA_BBOX,
                        "srs": "EPSG:4326"
                    }
                }
                if min_res is not None:
                    china_def["min_res"] = min_res
                if max_res is not None:
                    china_def["max_res"] = max_res
                config["sources"][china_source_name] = china_def
                sources_list.append(china_source_name)

            # Global Source (始终存在)
            global_source_name = f"{target_name}_global_source"
            global_def = {
                "type": "tile",
                "grid": self.GLOBAL_GRID_NAME,
                "url": global_url
            }
            if min_res is not None:
                global_def["min_res"] = min_res
            if max_res is not None:
                global_def["max_res"] = max_res
            config["sources"][global_source_name] = global_def
            sources_list.append(global_source_name)
            
            return sources_list

        # 3. 配置 Caches
        offline_mode = features_cfg.get("offline_mode", False)
        mbtiles_path = features_cfg.get("mbtiles_path", "./data/map_cache.mbtiles")

        def create_cache_def(is_offline, mbtiles_filepath, directory_path, cache_sources):
            c_def = {
                "grids": [self.GLOBAL_GRID_NAME],
                "sources": list(cache_sources),
                "format": "image/png",
                "meta_size": [4, 4],
                "meta_buffer": 128
            }
            if is_offline:
                if not os.path.isabs(mbtiles_filepath):
                    mbtiles_filepath = os.path.join(self.work_dir, mbtiles_filepath)
                os.makedirs(os.path.dirname(mbtiles_filepath), exist_ok=True)
                c_def["cache"] = {
                    "type": "mbtiles",
                    "filename": mbtiles_filepath
                }
            else:
                c_def["cache"] = {
                    "type": "file",
                    "directory": directory_path
                }
            return c_def

        # 为 Seed 任务创建独立缓存和对应的图层
        seeding_cfg = self.map_config.get("seeding", {})
        tasks = seeding_cfg.get("tasks")
        
        layers = []
        if isinstance(tasks, list) and tasks:
            for idx, task in enumerate(tasks):
                raw_name = task.get("name", f"task_{idx}")
                task_name = raw_name if raw_name else f"task_{idx}"
                task_cache_name = f"{task_name}_cache"
                
                # 动态限制图层访问层级
                min_res = None
                max_res = None
                zoom_levels = task.get("zoom_levels")
                if isinstance(zoom_levels, list) and len(zoom_levels) == 2:
                    min_zoom = int(zoom_levels[0])
                    max_zoom = int(zoom_levels[1])
                    min_res = float(self._get_res_for_zoom(min_zoom) * 1.0001)
                    max_res = float(self._get_res_for_zoom(max_zoom) * 0.9999)

                # 为当前任务生成带层级限制的 Sources
                task_sources = add_sources_for_target(task_name, min_res, max_res)
                
                # 动态生成各个任务的文件路径
                mbtiles_dir = os.path.dirname(mbtiles_path) if mbtiles_path else "./data"
                task_mbtiles_path = os.path.join(mbtiles_dir, f"{task_name}.mbtiles").replace("\\", "/")
                task_dir_path = f"./cache_data/{task_name}"
                
                config["caches"][task_cache_name] = create_cache_def(
                    offline_mode,
                    task_mbtiles_path,
                    task_dir_path,
                    task_sources
                )
                
                # 动态生成各个任务对应的图层
                layer_def = {
                    "name": task_name,
                    "title": task.get("title", f"Task Layer: {task_name}"),
                    "sources": [task_cache_name]
                }
                if min_res is not None:
                    layer_def["min_res"] = min_res
                if max_res is not None:
                    layer_def["max_res"] = max_res
                
                layers.append(layer_def)

        # 如果没有配置任务，则使用默认的回退图层
        if not layers:
            min_res = None
            max_res = None
            zoom_levels = seeding_cfg.get("zoom_levels")
            if isinstance(zoom_levels, list) and len(zoom_levels) == 2:
                min_zoom = int(zoom_levels[0])
                max_zoom = int(zoom_levels[1])
                min_res = float(self._get_res_for_zoom(min_zoom) * 1.0001)
                max_res = float(self._get_res_for_zoom(max_zoom) * 0.9999)
                
            default_sources = add_sources_for_target("default", min_res, max_res)
            
            config["caches"][self.CACHE_NAME] = create_cache_def(
                offline_mode, 
                mbtiles_path, 
                "./cache_data/arcgis_satellite",
                default_sources
            )
            
            layer_def = {
                "name": self.LAYER_NAME,
                "title": "Satellite Imagery",
                "sources": [self.CACHE_NAME]
            }
            if min_res is not None:
                layer_def["min_res"] = min_res
            if max_res is not None:
                layer_def["max_res"] = max_res
                
            layers.append(layer_def)
            
        config["layers"] = layers

        return config

    def generate_seed_config(self) -> Dict[str, Any]:
        """根据 map_config.json 生成 mapproxy-seed.yaml 的结构"""
        
        seeding_cfg = self.map_config.get("seeding", {})
        
        # 兼容两种模式：
        # 1. 旧模式：enabled, zoom_levels, bbox 直接在 seeding 下
        # 2. 新模式：tasks 列表，每个元素包含 name, levels, bbox, refresh_before
        
        # 默认空配置
        config = {
            "seeds": {},
            "coverages": {}
        }
        
        # 优先检查 tasks 列表
        tasks = seeding_cfg.get("tasks")
        if isinstance(tasks, list) and tasks:
            for idx, task in enumerate(tasks):
                # 任务名，去重
                raw_name = task.get("name", f"task_{idx}")
                task_name = raw_name if raw_name else f"task_{idx}"
                
                # BBOX
                bbox = task.get("bbox", self.CHINA_BBOX)
                coverage_name = f"{task_name}_bbox"
                config["coverages"][coverage_name] = {
                    "bbox": bbox,
                    "bbox_srs": "EPSG:4326"
                }
                
                # Zoom Levels
                levels = task.get("zoom_levels", [0, 8])
                
                # Refresh Time (Optional)
                refresh_time = task.get("refresh_before")
                if not refresh_time:
                    refresh_time = "2026-01-01T00:00:00"
                    
                task_cache_name = f"{task_name}_cache"
                    
                seed_def = {
                    "caches": [task_cache_name],
                    "grids": [self.GLOBAL_GRID_NAME],
                    "coverages": [coverage_name],
                    "levels": {
                        "from": levels[0],
                        "to": levels[1]
                    },
                    "refresh_before": {
                        "time": refresh_time
                    }
                }
                config["seeds"][task_name] = seed_def
                
            return config

        # 回退到单任务模式 (Legacy Compat)
        enabled = seeding_cfg.get("enabled", False)
        if not enabled:
            return config

        zoom_levels = seeding_cfg.get("zoom_levels", [0, 8])
        bbox = seeding_cfg.get("bbox", self.CHINA_BBOX)
        
        # 构造一个通用的 seed 任务
        task_name = "custom_seed_task"
        refresh_time = seeding_cfg.get("refresh_before")
        if not refresh_time:
            refresh_time = "2026-01-01T00:00:00"
        
        config["coverages"]["custom_bbox"] = {
            "bbox": bbox,
            "bbox_srs": "EPSG:4326"
        }
        
        config["seeds"][task_name] = {
            "caches": [self.CACHE_NAME],
            "grids": [self.GLOBAL_GRID_NAME],
            "coverages": ["custom_bbox"],
            "levels": {
                "from": zoom_levels[0],
                "to": zoom_levels[1]
            },
            "refresh_before": {
                "time": refresh_time
            }
        }
        
        return config

    def write_configs(self):
        """生成并写入配置文件"""
        mapproxy_cfg = self.generate_mapproxy_config()
        seed_cfg = self.generate_seed_config()
        
        mapproxy_path = os.path.join(self.work_dir, "mapproxy_config", "mapproxy.yaml")
        seed_path = os.path.join(self.work_dir, "mapproxy_config", "mapproxy-seed.yaml")
        
        os.makedirs(os.path.dirname(mapproxy_path), exist_ok=True)
        
        try:
            with open(mapproxy_path, 'w', encoding='utf-8') as f:
                yaml.dump(mapproxy_cfg, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
            self.logger.info(f"Generated mapproxy.yaml at {mapproxy_path}")
        except Exception as e:
            self.logger.error(f"Failed to write mapproxy.yaml: {e}")
            raise

        try:
            with open(seed_path, 'w', encoding='utf-8') as f:
                yaml.dump(seed_cfg, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
            self.logger.info(f"Generated mapproxy-seed.yaml at {seed_path}")
        except Exception as e:
            self.logger.error(f"Failed to write mapproxy-seed.yaml: {e}")
            raise

