seeds:
  arcgis_low_zoom:  # 全球范围，0-5 级
    caches: [arcgis_satellite_cache]
    grids: [webmercator]
    coverages: [world]
    levels:
      from: 0
      to: 5
    refresh_before:
      time: 2026-01-01T00:00:00  # 设置一个过去的时间，确保只生成缺失的，不强制刷新
      
  arcgis_china_mid_zoom:  # 中国区域，6-12 级
    caches: [arcgis_satellite_cache]
    grids: [webmercator]
    coverages: [china_bbox]
    levels:
      from: 6
      to: 12
    refresh_before:
      time: 2026-01-01T00:00:00

coverages:
  world:
    bbox: [-180.0, -90.0, 180.0, 90.0]
    bbox_srs: EPSG:4326
  china_bbox:
    bbox: [73.0, 18.0, 135.0, 54.0]
    bbox_srs: EPSG:4326
